<a href="https://colab.research.google.com/github/Sneha-code01/Python/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy is a mathematical library used for scientific computing. this encapsulates n-dimensional arrays of homogeneous data types.
#numpy array v/s python sequences
#1. numpy array have fixed size at creation unlinke python lists
#2.all element in numpy array are all required to be the same data type
#3. various scientific and mathematical package of pyhton are usig numpy arrays these support python-sequential input they convert that to array before processing.

In [ ]:
#creating numpy array
import numpy as np

a = np.array([1,2,3,4])#vector
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#2d and 3d array
b = np.array([[1,2,3],[4,5,6]])#matrix
print(b)
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#tensor
print(c)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#dtype ie used to write float,bolean,complex type
d = np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [ ]:
#dtype ie used to write float,bolean,complex type
e = np.array([1,2,3],dtype=bool)
print(e)

[ True  True  True]


In [ ]:
#np.arrange just like range funct of python
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
#with reshape change row column in array
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [ ]:
#np.ones make numpy array with all item is 1 used in tensorflow for intializing fastly
#np.zeros, np.random
np.ones((3,5))
np.zeros((4,3))
np.random.random((5,3))

array([[0.19579711, 0.13082808, 0.51921852],
       [0.23059796, 0.59037313, 0.70243331],
       [0.20751439, 0.81048991, 0.08325508],
       [0.76821233, 0.56050558, 0.37414192],
       [0.2585871 , 0.61778526, 0.04396203]])

In [ ]:
#np.linspace (lower range, upper range, nos generate b/w them) equal dist pe point generate karta hai
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [ ]:
#np.identity have diagonal item 1 and rest 0
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])